# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reg_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reg_msgs.proto',
  package='reg_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ereg_msgs.proto\x12\x08reg_msgs\"\\\n\x07RegInfo\x12\x0e\n\x06hostID\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65stID\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x11\n\tis_server\x18\x04 \x01(\x08\x12\x11\n\tbind_port\x18\x05 \x01(\x05\x62\x06proto3')
)




_REGINFO = _descriptor.Descriptor(
  name='RegInfo',
  full_name='reg_msgs.RegInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostID', full_name='reg_msgs.RegInfo.hostID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destID', full_name='reg_msgs.RegInfo.destID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='reg_msgs.RegInfo.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_server', full_name='reg_msgs.RegInfo.is_server', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_port', full_name='reg_msgs.RegInfo.bind_port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['RegInfo'] = _REGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegInfo = _reflection.GeneratedProtocolMessageType('RegInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGINFO,
  '__module__' : 'reg_msgs_pb2'
  # @@protoc_insertion_point(class_scope:reg_msgs.RegInfo)
  })
_sym_db.RegisterMessage(RegInfo)


# @@protoc_insertion_point(module_scope)
