// Generated by gencpp from file autoware_msgs/DroneSyn.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_DRONESYN_H
#define AUTOWARE_MSGS_MESSAGE_DRONESYN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autoware_msgs
{
template <class ContainerAllocator>
struct DroneSyn_
{
  typedef DroneSyn_<ContainerAllocator> Type;

  DroneSyn_()
    : header()
    , gps()
    , imu()  {
      gps.assign(0.0);

      imu.assign(0.0);
  }
  DroneSyn_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps()
    , imu()  {
  (void)_alloc;
      gps.assign(0.0);

      imu.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 6>  _gps_type;
  _gps_type gps;

   typedef boost::array<double, 7>  _imu_type;
  _imu_type imu;





  typedef boost::shared_ptr< ::autoware_msgs::DroneSyn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::DroneSyn_<ContainerAllocator> const> ConstPtr;

}; // struct DroneSyn_

typedef ::autoware_msgs::DroneSyn_<std::allocator<void> > DroneSyn;

typedef boost::shared_ptr< ::autoware_msgs::DroneSyn > DroneSynPtr;
typedef boost::shared_ptr< ::autoware_msgs::DroneSyn const> DroneSynConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::DroneSyn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::DroneSyn_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_msgs::DroneSyn_<ContainerAllocator1> & lhs, const ::autoware_msgs::DroneSyn_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gps == rhs.gps &&
    lhs.imu == rhs.imu;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_msgs::DroneSyn_<ContainerAllocator1> & lhs, const ::autoware_msgs::DroneSyn_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::DroneSyn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::DroneSyn_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::DroneSyn_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbadf538072dc3bef18cfe582f63dae4";
  }

  static const char* value(const ::autoware_msgs::DroneSyn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbadf538072dc3beULL;
  static const uint64_t static_value2 = 0xf18cfe582f63dae4ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/DroneSyn";
  }

  static const char* value(const ::autoware_msgs::DroneSyn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64[6] gps   \n"
"float64[7] imu\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::autoware_msgs::DroneSyn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps);
      stream.next(m.imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneSyn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::DroneSyn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::DroneSyn_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps[]" << std::endl;
    for (size_t i = 0; i < v.gps.size(); ++i)
    {
      s << indent << "  gps[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gps[i]);
    }
    s << indent << "imu[]" << std::endl;
    for (size_t i = 0; i < v.imu.size(); ++i)
    {
      s << indent << "  imu[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.imu[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_DRONESYN_H
