# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd_msgs.proto',
  package='cmd_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63md_msgs.proto\x12\x08\x63md_msgs\"\x1b\n\x03\x43md\x12\t\n\x01v\x18\x01 \x01(\x01\x12\t\n\x01w\x18\x02 \x01(\x01\x62\x06proto3')
)




_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='cmd_msgs.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='cmd_msgs.Cmd.v', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='cmd_msgs.Cmd.w', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), {
  'DESCRIPTOR' : _CMD,
  '__module__' : 'cmd_msgs_pb2'
  # @@protoc_insertion_point(class_scope:cmd_msgs.Cmd)
  })
_sym_db.RegisterMessage(Cmd)


# @@protoc_insertion_point(module_scope)
