# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone_cmd_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drone_cmd_msgs.proto',
  package='drone_cmd_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x64rone_cmd_msgs.proto\x12\x0e\x64rone_cmd_msgs\"a\n\x08\x44roneCmd\x12\n\n\x02vx\x18\x01 \x01(\x01\x12\n\n\x02vy\x18\x02 \x01(\x01\x12\n\n\x02vz\x18\x03 \x01(\x01\x12\n\n\x02wz\x18\x04 \x01(\x01\x12%\n\x04\x66lag\x18\x05 \x01(\x0e\x32\x17.drone_cmd_msgs.CmdType*:\n\x07\x43mdType\x12\x08\n\x04\x41UTO\x10\x00\x12\n\n\x06MANUAL\x10\x01\x12\x0c\n\x08TAKE_OFF\x10\x02\x12\x0b\n\x07LANDING\x10\x03\x62\x06proto3')
)

_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='drone_cmd_msgs.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKE_OFF', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LANDING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
AUTO = 0
MANUAL = 1
TAKE_OFF = 2
LANDING = 3



_DRONECMD = _descriptor.Descriptor(
  name='DroneCmd',
  full_name='drone_cmd_msgs.DroneCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vx', full_name='drone_cmd_msgs.DroneCmd.vx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vy', full_name='drone_cmd_msgs.DroneCmd.vy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vz', full_name='drone_cmd_msgs.DroneCmd.vz', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wz', full_name='drone_cmd_msgs.DroneCmd.wz', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='drone_cmd_msgs.DroneCmd.flag', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=137,
)

_DRONECMD.fields_by_name['flag'].enum_type = _CMDTYPE
DESCRIPTOR.message_types_by_name['DroneCmd'] = _DRONECMD
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DroneCmd = _reflection.GeneratedProtocolMessageType('DroneCmd', (_message.Message,), {
  'DESCRIPTOR' : _DRONECMD,
  '__module__' : 'drone_cmd_msgs_pb2'
  # @@protoc_insertion_point(class_scope:drone_cmd_msgs.DroneCmd)
  })
_sym_db.RegisterMessage(DroneCmd)


# @@protoc_insertion_point(module_scope)
